# workflow name
name: Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the wanted branches
on: push


  linux_docker_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_tags: ['final-3_34_0','ltr', 'stable', 'latest']
      fail-fast: false

    container:
      image: qgis/qgis:${{ matrix.docker_tags }}
      env:
        QGIS_PLUGIN_IN_CI: 1
        PIP_BREAK_SYSTEM_PACKAGES: 1

    steps:
      - name: QGIS Version Information
        run: qgis --version

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Environment
        run: |
          pip3 install pytest-qgis

      - name: Run Tests
        run: xvfb-run -s '+extension GLX -screen 0 1024x768x24' python3 -m pytest -v --doctest-glob='' -m "not needs_wntr and not needs_pandas"


  windows_choco:
    runs-on: windows-latest
    strategy:
      matrix:
        qgis_version: ['3.40.0','3.44.0','4.0.0']
      fail-fast: false
    env:
      QGIS_PLUGIN_IN_CI: 1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Choco install qgis
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install qgis --version=${{ matrix.qgis_version }} -y

      - name: Setup Pytest-QGIS
        shell: pwsh
        run: |
          $env:PATH="C:\Program Files\QGIS ${{ matrix.qgis_version }}\bin;$env:PATH"
          python-qgis.bat -m pip install pytest-qgis

      - name: Run Tests
        shell: pwsh
        run: |
          $env:PATH="C:\Program Files\QGIS ${{ matrix.qgis_version }}\bin;$env:PATH"
          python-qgis.bat -m pytest -v -m "not needs_wntr and not needs_pandas"

